services:
  - type: web
    name: nodejs-app
    env: docker
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: mysql
