# render.yaml
services:
  - type: pserv
    name: mysql
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - fromGroup: mysql

  - type: web
    name: nodejs-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - fromGroup: mysql

envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_DATABASE
        value: mysql
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        value: rudramanu
